invest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('stocks/', include('stocks.urls')),
    path('admin/', admin.site.urls),
]

stocks/urls.py
from django.urls import path

from . import views

app_name = 'stocks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<str:stock_name>/', views.detail, name='detail'),
    path('<str:stock_name>/data_api', views.detail_as_json, name='detail_as_json'),
    path('<str:stock_name>/data', views.detail_as_json, name='detail_from_elastic_json'),

]

stocks/models.py
from django.db import models


class Stock(models.Model):
    name = models.CharField(max_length=8, primary_key=True)
    long_name = models.CharField(max_length=128)
    created = models.DateTimeField('created')

    def __str__(self):
        return self.name

stocks/views.py
import datetime

from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import JsonResponse
from .models import *
from clients.elastic_client import ElasticClient
from constans.constans import *
from clients.alpha_client import AlphaClient


class IndexView(generic.ListView):
    template_name = 'stocks/index.html'
    context_object_name = 'stocks_list'

    def get_queryset(self):
        """Return the last five"""
        return Stock.objects.order_by('-created')[:5]


def detail(request, stock_name):
    stock = get_object_or_404(Stock, name=stock_name)
    return render(request, 'stocks/detail.html', {'stock': stock})


def detail_as_json(request, stock_name):
    date = []
    open = []

    c = AlphaClient("EGS9M9PKVRPCC946")
    status, body = c.get_stock_from_api(stock_name)

    time_serie_key = "Time Series (5min)"
    for k in body[time_serie_key]:
        date.append(k)
        open.append(body[time_serie_key][k]["1. open"])
    return JsonResponse(data={
        'date': date,
        'open': open,
    })


def detail_from_elastic_json(request, stock_name):
    date = []
    open = []

    elastic = ElasticClient()

    result = elastic.client.search(index="stock-{}".format(stock_name), body={
        "query": {
            "range": {
                "timestamp": {
                    "lt": datetime.datetime.now()
                }
            }
        },
    })

    for hit in result["hits"]["hits"]:
        date.append(hit["_source"][TIMESTEAMP])
        open.append(hit["_source"][OPEN])

    return JsonResponse(data={
        'date': date,
        'open': open,
    })

stocks/templates/stocks/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ stock.name }}</h1>
<h1>{{ stock.long_name }}</h1>
<h1>{{ stock.created }}</h1>



  <div id="container" style="width: 75%;">
    <canvas id="stock-chart" data-url="{% url 'stocks:detail_as_json' stock.name %}"></canvas>
  </div>

  <div id="container2" style="width: 75%;">
    <canvas id="stock-chart2" data-url="{% url 'stocks:detail_from_elastic_json' stock.name %}"></canvas>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $stockChart = $("#stock-chart");
      console.log("URL"+$stockChart.data("url"))
      $.ajax({
        url: $stockChart.data("url"),
        success: function (data) {
          var ctx = $stockChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.date,
              datasets: [{
                label: 'Stock',
                backgroundColor: 'blue',
                data: data.open
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Stock Data from Alpha API'
              }
            }
          });

        }
      });

    });






    $(function () {

      var $stockChart = $("#stock-chart2");
      $.ajax({
        url: $stockChart.data("url"),
        success: function (data) {
          var ctx = $stockChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.date,
              datasets: [{
                label: 'Stock Oprn',
                backgroundColor: 'blue',
                data: data.open
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Stock Data from Elastic'
              }
            }
          });

        }
      });

    });
  </script>




{{ stock.data }}

</body>
</html>

stocks/templates/stocks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if stocks_list %}
    <ul>
    {% for s in stocks_list %}
        <li><a href="{% url 'stocks:detail' s.name %}">{{ s.long_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No stocks are available.</p>
{% endif %}

</body>
</html>